name: Deploy Next.js app to Azure

on:
  push:
    branches:
      - main  # ← デプロイ対象ブランチ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをクローン
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Node.js セットアップ（必要に応じてバージョン変更）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3. パッケージインストール
      - name: Install dependencies
        run: npm install

      # 4. ビルド
      - name: Build Next.js app
        run: npm run build

      # 5. デプロイ用ファイルの準備
      # 5. 必要ファイルを deploy ディレクトリにコピー
      - name: Copy standalone output to deploy
        run: |
          mkdir -p deploy/.next
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static || true
          cp .next/BUILD_ID deploy/.next/BUILD_ID
          cp .next/routes-manifest.json deploy/.next/routes-manifest.json
          cp .next/prerender-manifest.json deploy/.next/prerender-manifest.json || true
          cp next.config.js deploy/
          cp package.json deploy/
          cp server.js deploy/

      # 6. Azure にデプロイ
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-step4-64 # AzureのApp Service名に置き換えてください
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy


# name: Build and deploy Node.js app to Azure Web App - app-step4-64

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read #This is required for actions/checkout

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20.x'

#       - name: npm install, build, and test
#         #1
#         env:
#           NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
#         run: |
#           npm install
#           npm run build --if-present
#           npm run test --if-present

#       #2
#       - name: Copy artifact for deployment job
#         run: |
#           mkdir deploy
#           cp -r ./.next/standalone/. ./deploy
#           cp -r ./.next/static/. ./deploy/.next/static

#       - name: Zip artifact for deployment
#         run: zip release.zip ./* -r

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: node-app
#           path: release.zip

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: node-app

#       - name: Unzip artifact for deployment
#         run: unzip release.zip

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'app-step4-64'
#           slot-name: production
#           package: ./deploy
