name: Deploy Next.js app to Azure

on:
  push:
    branches:
      - main  # ← デプロイ対象ブランチ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをクローン
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Node.js セットアップ（必要に応じてバージョン変更）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3. パッケージインストール
      - name: Install dependencies
        run: npm install

      # 4. ビルド
      - name: Build Next.js app
        run: npm run build

      # 5. デプロイ用ファイルの準備
      # 5. 必要ファイルを deploy ディレクトリにコピー
      - name: Copy standalone output to deploy
        run: |
          mkdir -p deploy
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static
          cp package.json deploy/
          cp next.config.js deploy/ || true

      # 6. Azure にデプロイ
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-step4-64 # AzureのApp Service名に置き換えてください
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy